### ISSUE TITLE
Mp4 file stutters when 3 images + 1 text label are displayed

### ISSUE THREAD

**Issue by zontarian** [dividuum/info-beamer-nodes#10]
Hello,

I've built a node based on the `intermission` example. At the moment when nothing happens a loop MP4 file is played (loaded via raw video). Sometimes an external actions causes the video to pause and to display on the monitor 2 images and a label (one is full screen), and on top of that another "priority" image (2048 max). Everything works as expected.

But sometimes while the 4 items (3 images + a text label) are displayed, an audio file need to be played. It's actually an MP4 file, with a static image and mono audio. The audio starts correctly but after a few seconds the audio lags horrendously, and slows down 2x or 3x.. 

If I display only the 3 items without the priority image, the audio plays smoothly.
I'm running on a RaspberryPiZero powered by USB from another RaspberryPi 3B.

Is it a power issue? Should I power the raspberry independently? I could not try since I lack a power adapter right now, but this is the first thing that came to my mind.

Is it a processor issue? Too many things are displayed? Should I lower the resolution of some image, since my monitor is only fullHD and I can reduce safely the sizes to 1/4 (1080x1080)? 

Any other idea?
THanks

Walter

**Comment by dividuum** [comment]
Interesting. I never had audio slow down. But displaying a lot at once certainly puts a lot of load on the GPU. What the frame rate while displaying all your content? Is it still at 60? Using images identical to the target resolution certainly helps at bit, so I suggest you try that first. You can also use `INFOBEAMER_SWAP_INTERVAL=2` to see how everything works if you go down to 30fps. Power might be an issue, but that would usually result in a visual indicator on screen.

**Comment by zontarian** [comment]
Hi. Interesting is not what I said :)

Ok.. I was aware of the visual indicator (the Harry Potter flash icon).. but there is no such.
I've tried with `INFOBEAMER_SWAP_INTERVAL=2` but to me it seems the same. It stutters after a few seconds.. 

Btw, is there an audio only file format ? I've tried with WAV but it's not played, so I've used iMovie (!!) to create a video with a fake image and the audio track.. and exported it to mp4.

Now I'll try resizing.
Thanks

**Comment by zontarian** [comment]
Ok.. after reducing image from 1900x2048 to almost half each size.. it works a little longer before stuttering. 8 seconds instead of 4.. 

As a side note, I've tried to reduce the number of images loaded at any given time.
Now I have only a background image, a priority image and the mp4. Everything else is swapped out, discarded, a part ffrom the loop video which is paused.

Again, this results in a longer time of normal audio (20 sec?) and the stutter takes longer to appear, but it appears anyway..  :(

Weird thing is.. If I play a proper video +audio instead of fake video+audio, of about the same size on disk, but without the priority image, the video is supersmooth..

**Comment by zontarian** [comment]
As a side note, I've tried to reduce the number of images loaded at any given time.
Now I have only a background image, a priority image and the mp4. Everything else is swapped out, discarded, a part ffrom the loop video which is paused.

Again, this results in a longer time of normal audio (20 sec?) and the stutter takes longer to appear, but it appears anyway..  :(

**Comment by dividuum** [comment]
Could you send me the node directory, so I can try to run it on one of my Pis?

**Comment by zontarian** [comment]
Mh.. not really. It's my customer copyrighted material but, most important, it's 1.5 GB in around 340 files. 
I've solved by treating this edge case with a trick: instead of composing two images (1020x800) I show an already composed image (just one) and the audio plays smoothly.. 

If you think I could share only the relevant files privately?

**Comment by dividuum** [comment]
Understood. The workaround is a good idea in general. The Pi isn't too powerful and the more you can "cheat" the better. Sure about sharing the files privately (and offering any result publicly).

**Comment by zontarian** [comment]
In the end with the good help of @dividuum , we ended using a simple MP4 file with a transparent still image. This way the decoding is lighter and it works.

This is the script we used to pass from `wav` to `mp4`

```
ffmpeg -y -i original.wav audio_only.aac # get audio part
ffmpeg -y -loop 1  -i blank.png -i audio_only.aac -c:v libx264 -r 5 -b:v 10000 -pix_fmt yuv420p -c:a copy -shortest only_audio.mp4
```

`blang.png` is a simple 16x16 transparent PNG 

Thanks!
