### ISSUE TITLE
Database connection Sqlite3

### ISSUE THREAD

**Issue by RajshekharHoratti** [dividuum/info-beamer-nodes#3]
We are trying to play a video files, where in the names are stored in sqlite database.

Tried connecting to sqlite db from node.lua but throws 'a nil value' ran into all sorts of errors. Whilst the same works on command line lua interpreter.  

Is there any sample snippets where info-beamer can connect to sqite db.

Kindly help.

**Comment by dividuum** [comment]
info-beamer can't open sqlite3 database files.

Is there anything else stored in the sqlite db besides the filenames? Like duration or order? If not, I'd suggest you just put all the video files next to the node.lua file. That way, all filenames will end up in the [CONTENTS table](https://info-beamer.com/doc/info-beamer#CONTENTS) in Lua which you can then use to find all video files. Code that does something similar is in https://github.com/dividuum/info-beamer-nodes/blob/master/photos/node.lua, except it's filtering out all jpg files instead of video files.

If you also store metadata in that database, I'd suggest you have some kind of preprocessing step that uses the database to write all required metadata into a json file, then (hard)links all videos and the node.lua file into an output directory. It's content might then look like this:

```
video1.mp4
video2.mp4
videos.json
node.lua
```

In node.lua you react to changes to the `videos.json` using for example [file_watch](https://info-beamer.com/doc/info-beamer#util.file_watch) to [re-read](https://info-beamer.com/doc/info-beamer#resource.load_file) the metadata you can then use to access and play the video files. The benefit of this approach is that you can rsync the output directory to as many devices as you need as it contains everything required to play the content. I've successfully used this approach many times and it works great and is very reliable.

**Comment by RajshekharHoratti** [comment]
Thanks for your suggestion i was able to access the json files and trying to create dynamic "VideoIDs"   when i tried to send a UDP packet with any of the VideoIDs it always plays the last Video 

`node.event("content_update", function(filename)
    if filename == "data.json" then
        local datadecode = json.decode(resource.load_file(filename))
        test = resource.load_file(filename)
        print(test)
        for _, v in ipairs(datadecode) do
            VideoID = v.VideoID
            print(VideoID)
            VideoFile = v.file
	    print(VideoFile)
            VideoID = Test (VideoFile)

        end

    end
end)
`
kindly help i am new to lua programming 
thanks :)

**Comment by dividuum** [comment]
You code snippet is lacking a bit of context, so I can only provide limited help. What is `Test(...)` doing? If your `data.json` file contains an array of objects, like this:

```
[
    {"VideoID": "foobar", "file": "video1.mp4"},
    ...
]
```

your code seems correct. What are you doing in the UDP handler? Although, if the `VideoID` is guaranteed to be unique, you might want to use something like this instead:

```
{
     "foobar": {"file": "video1.mp4"},
     ...
}
```

That way you can easily access the data assigned to a VideoID by just doing:

```
local video_file = datadecode[videoid].file
```

Btw: You can click on the preview tab while writing a comment here to see what it will look like and avoid misformatted markdown.

**Comment by RajshekharHoratti** [comment]
Thanks :) but what i really wanted to do is in UDP handler i just want to send the VIdeoID and the respective Video file should be played and i want to make them dynamic.

Test Function is just loading the VideoFiles and assigning them to their respective VideoID's but here it is just loading only the last video i want all the videos should be loaded dynamically which are in the data.json file so that with only the respective VideoID's i could play any video 

`
Test = function(file)
    local vid = resource.create_colored_texture(0, 0, 0, 0)
    local function draw()
        util.draw_correct(vid, 0, 0, WIDTH, HEIGHT)
        return vid:state() ~= "finished"
    end

    local function preload()
        if vid then vid:dispose() end
        vid = resource.load_video(file, false, false, true)
    end

    local function set_running(running)
        if running then
            preload()
            vid:start()
        else
            preload()
        end
    end

    preload()

    return {
        draw = draw;
        set_running = set_running;
    }
end`

I had tried the preview but its not taking the full code,
and again thanks for your Response :)

**Comment by dividuum** [comment]
You have to store the result of calling `Test` somewhere: I'd suggest you use this approach:

```
local videos = {}

node.event("content_update", function(filename)
    if filename == "data.json" then
        local data = json.decode(resource.load_file(filename))
        videos = {} -- reset the table, so it can be filled again
        for _, v in ipairs(datadecode) do
            videos[v.VideoID] = Video(v.file)
        end
    end
end)

local function Video(file)
     -- the body of the Test function in your comment
end
```

In the UDP handler you can the access the Video "object" for each video by its `VideoID` like this:

```
local video = videos[VideoId]
-- do something with the video here
```

**Comment by RajshekharHoratti** [comment]
Thanks :) All the video files and getting loaded but  now only the last video file is getting played

```
local videos = {}
node.event("content_update", function(filename)

    if filename == "data.json" then
        local data = json.decode(resource.load_file(filename))
        videos = {} -- reset the table, so it can be filled again
        for _, v in ipairs(data) do
            VideoID = v.VideoID
            VideoID2String = tostring(v.VideoID)
            videos[v.VideoID] = Test(v.file)
        end
    end
end)
```

```
local function start_play()

    local video = videos[VideoID2String]
    video.set_running(true)
    surface = video
end
```

```
util.data_mapper {

    ["set"] = function(new_mode)
        print(new_mode)
        if new_mode == VideoID then
            start_play()
        else
            print("!!!!!!!!!!!!!!!!!--ERROR--!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
        end
    end;
```
here consider "f3001" is the VideoID 

`echo -n "looper00/set:f3001" > /dev/udp/localhost/4444`

**Comment by dividuum** [comment]
There are multiple problems with your current approach:

 * You loop through the `data` table in the `content_update` event handler and overwrite the global variables `VideoID` and `VideoID2String` in each iteration.
 * `start_play` has no arguments but used the global `VideoID2String` variable. Which contains the value from the last assignment from the loop (see previous point)
 * In the `"set"` callback you compare `new_mode` to `VideoID` which also contains the last assigned value from that loop. So it only matches when you provide the VideoID of the last video in your `data.json` file.

Just use the `videos` table generated in the `content_update` handler and use it in the `"set"` callback like this:

```
local function start_play(video)
    video.set_running(true)
    surface = video
end

["set"] = function(VideoID)
    start_play(videos[VideoID])
end
```

This help is all based on limited knowledge of your complete code, as you didn't provide that. So it might be totally wrong.

**Comment by RajshekharHoratti** [comment]
Appreciate your help, Thanks for your time. Your solutions worked as expected.
