### ISSUE TITLE
Digital clock

### ISSUE THREAD

**Issue by fenhl** [dividuum/info-beamer-nodes#6]
I'm trying to figure out how to make a digital clock that works on both the pi version and the opensource version. An example would be much appreciated.

**Comment by dividuum** [comment]
https://github.com/dividuum/info-beamer-nodes/blob/master/analogclock/node.lua is an example for an analog clock. Just use the `hour`, `minute` and `seconds` and [write](https://info-beamer.com/doc/info-beamer#font.write) them on the screen.
