### ISSUE TITLE
Resume/restart playback of a video from first frame?

### ISSUE THREAD

**Issue by zontarian** [dividuum/info-beamer-nodes#9]
Hello.
I'm using Info-beamer on a RaspberryPi Zero and everything is ok. 
But right now I'd like to solve two issues:
1. after pausing a video, I'd like to resume playing it from the beginning, not from the frame next to when I stopped it.
2. I'd like to play a video in a loop but just for a given number of repetitions.

At the moment the only solution I'm aware of is to reload the video.. but it seems to me useless to reload a video that should already be in memory in some form or another.. 
so what I am looking for is a function like `rewind` before  `start`.

For example I have this code which checks if a video has finished playing.
```
    if watch_more and watch_more:state() == 'finished' and blank_before_more == 0 then
        -- play watch more
        print("watch more finished " .. count_watch_more)

        --decrement
        count_watch_more = count_watch_more - 1

        if count_watch_more == 0 then
            watch_more:dispose()
            watch_more = nil
            -- do other things
            continue_main_loop()
        else
            -- play again ??? how without reloading
        end
    end
```

This should play the watch_more video `count_watch_more` times, until the counter reaches zero. How can I achieve this without writing `watch_more = raw.load_video("watch-more.mp4", false, false)`

Btw, I'm using as a starting point the `intermissions-many` example. 

Thanks
W

**Comment by dividuum** [comment]
Sorry for the delay. Right now there's no way to directly solve that you're trying to do. Looping a specified number of times requires you to recreate a video object each time, as there's no way to count or limit the loops for a video started with `looped = true`.

I might look into that though as it might sound useful for certain projects.

**Comment by zontarian** [comment]
Hi Florian,
no problem. Ok I am aware there is no way right now, and in fact what I have tried is to have a counter and use it to reload the video a number of times. Unfortunately the second time the video does not display.. 

But this was just half of the quetion. the other half was how to resume a video (specifically the loop in the example `intermission-many` not from where it was paused, but from the beginning? Is it even possible? 

Thanks, the product is very nice and it is amazingly stable and powerful.

**Comment by dividuum** [comment]
Unfortunately there is also ~to~ no `:restart()` or `:seek(0)` method for videos that would allow you to restart an already loaded video object. If you don't need seamless video playback, you might just solve your use case by only ever having one video loaded and playing. When it ends, you'd unload it and then start the loop video. If you want to interrupt the playback with another video, you'd stop the current video and replace it. Would that work?

**Comment by zontarian** [comment]
Hi.. you do mean that there are not `:restart` or `:seek(0)`? Or there are, but it is an unfortunate thing?
At the moment I've bypassed the problem ignoring it. in the future I will try reloading each time, thanks!

**Comment by dividuum** [comment]
They don't exist at the moment. I've fixed the typo.
